spring:
  application:
    name: pi
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:pi
  h2:
    console:
       enabled: true
       settings:
        web-allow-others: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

server.port: 8085


