CREATE TABLE ADDRESS (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
  city VARCHAR(255) NOT NULL,
  postal_code VARCHAR(30) NOT NULL,
  state VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL
);

CREATE TABLE PRIVILEGES (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
  caption VARCHAR(50) NOT NULL,
  can_view BOOLEAN NOT NULL,
  can_create BOOLEAN NOT NULL,
  can_update BOOLEAN NOT NULL,
  can_remove BOOLEAN NOT NULL
);

CREATE TABLE ACCOUNT (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  privileges_id BIGINT NOT NULL
);

CREATE TABLE CUSTOMER (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  account_id BIGINT NOT NULL,
  address_id BIGINT NOT NULL
);

CREATE TABLE PROFESSION (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  designation VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  profession_id BIGINT NOT NULL,
  employment_date DATE NOT NULL,
  salary_gross_id BIGINT NOT NULL
);

CREATE TABLE PRICE (
  id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  value FLOAT NOT NULL,
  currency VARCHAR(10) NOT NULL
);
