spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mi
  h2:
    console:
       enabled: true
       settings:
        web-allow-others: true

server.port: 8082



